### ISSUE TITLE
Subtitle issue

### ISSUE THREAD

**Issue by seadogro** [mattlyon93/filter-subs#6]
Hi, thanks for your tool. Unfortunately it seems as the tool somehow can't manage to delete
empty "." points in a subtitle + it seems through that to delete half of the subtitle.
I tried with this subtitle here
https://www.opensubtitles.org/en/subtitles/8693442/queen-of-the-south-a-prueba-de-balas-en

When i do it it removes half the subtitle. I don't know why. If it are just the "." dots or if it is anything else.

Please check if you get the same result if you remove sdh's in the sub above.
Thank you already in advance.

**Comment by mattlyon93** [comment]
I tried it with the subtitle file you suggested, and the filtered version looks pretty good to me.
Could you paste a before and after of a specific line that is not handled well?

Thanks

**Comment by seadogro** [comment]
When i try it i get a completely small file. Basically it erases me everything down to 1kb. And i don't know why. 
Best Regards.

**Comment by mattlyon93** [comment]
>  What the tool also can't remove is "< i >" "< / i >" signs in the subtitle.

Yes indeed the tool does not remove italics as they don't take away from the subtitle experience in my opinion, though if that is a requested feature then it would certainly possible to include that functionality.

> When i try it i get a completely small file. Basically it erases me everything down to 1kb.

This is quite strange. Using the previously mentioned subtitle file, I got the filtered version file size to around 42kb from 50kb originally.

Could you paste a before and after from the first few lines of the subtitle file? If you include the flag `-p` in the commandline prompt, for example
`filter-subtitles.py -p -s /my/subtitle/file.srt`
this will print the output instead of saving it to file.

**Comment by seadogro** [comment]
> 
> 
> > What the tool also can't remove is "< i >" "< / i >" signs in the subtitle.
> 
> Yes indeed the tool does not remove italics as they don't take away from the subtitle experience in my opinion, though if that is a requested feature then it would certainly possible to include that functionality.
> 
> > When i try it i get a completely small file. Basically it erases me everything down to 1kb.
> 
> This is quite strange. Using the previously mentioned subtitle file, I got the filtered version file size to around 42kb from 50kb originally.
> 
> Could you paste a before and after from the first few lines of the subtitle file? If you include the flag `-p` in the commandline prompt, for example
> `filter-subtitles.py -p -s /my/subtitle/file.srt`
> this will print the output instead of saving it to file.
It seems fixxed with output it works. Maybe it was the srt file itself. Anyways it is solved, thanks :).
